name: Docker Compose CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build & Start Docker Compose
      run: docker compose up -d --build

    - name: Run backend tests
      run: docker compose exec backend mvn test

    - name: Stop Docker Compose
      run: docker compose down
